INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1001, 'USD','INR',78.89,0)

INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1002, 'UKP','INR',79.89,0)

INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1003, 'AUD','INR',77.89,0)