INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1005, 'USD','INR',78.89,0)

INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1006, 'UKP','INR',79.89,0)

INSERT INTO EXCHANGE_VALUE (ID ,CURRENCY_FROM ,CURRENCY_TO ,CONVERSION_MULTIPLE ,APPLICATION_PORT ) VALUES (1007, 'AUD','INR',77.89,0)